---
kind: ConfigMap
apiVersion: v1
metadata:
  name: fms-orchestr8-config-nlp
  annotations:
    helm.sh/weight: "0"
data:
  config.yaml: |
    openai: 
      service:
        hostname: llama-32-predictor
        port: 8080
    detectors:
      regex_competitor:
        type: text_contents
        service:
            hostname: "127.0.0.1"
            port: 8080
        chunker_id: whole_doc_chunker
        default_threshold: 0.5
      hap:
        type: text_contents
        service:
          hostname: guardrails-detector-ibm-hap-predictor
          port: 8000
        chunker_id: whole_doc_chunker
        default_threshold: 0.5
      prompt_injection:
        type: text_contents
        service:
          hostname: prompt-injection-detector-predictor
          port: 8000
        chunker_id: whole_doc_chunker
        default_threshold: 0.5
      language_detection:
        type: text_contents
        service:
          hostname: language-detector-predictor
          port: 8000
        chunker_id: whole_doc_chunker
        default_threshold: 0.75
