---
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    helm.sh/weight: "0"
    opendatahub.io/accelerator-name: ''
    opendatahub.io/apiProtocol: REST
    opendatahub.io/template-display-name: vLLM
    opendatahub.io/template-name: vllm
    openshift.io/display-name: llama-32
  name: llama-32
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  builtInAdapter:
    modelLoadingTimeoutMillis: 90000
  containers:
    - args:
        - '--dtype=half'
        - '--gpu-memory-utilization=0.95'
        - '--enable-chunked-prefill'
        - '--port=8080'
        - '--model=/mnt/models'
        - '--served-model-name=llama32'
        - '--max-model-len'
        - '512'
        - '--max-output-tokens'
        - '300' 
        - '--max-num-seqs'
        - '384'
        - '--max-num-batched-tokens'
        - '12288
      env:
        - name: VLLM_CONFIG_ROOT
          value: /tmp
      image: 'quay.io/modh/vllm:rhoai-2.19-cuda'
      name: kserve-container
      ports:
        - containerPort: 8080
          name: http1
          protocol: TCP
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: pytorch
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    helm.sh/weight: "1"
    openshift.io/display-name: llama-32
    serving.kserve.io/deploymentMode: RawDeployment
  name: llama-32
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    automountServiceAccountToken: false
    maxReplicas: 1
    minReplicas: 0
    model:
      args:
        - '--enable-auto-tool-choice'
        - '--tool-call-parser=llama3_json'
      modelFormat:
        name: pytorch
      name: ''
      resources:
        limits:
          cpu: '4'
          memory: 20Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '1'
          memory: 8Gi
          nvidia.com/gpu: '1'
      runtime: llama-32
      storageUri: 'oci://quay.io/redhat-ai-services/modelcar-catalog:llama-3.2-3b-instruct'
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        value: Tesla-T4-SHARED
